### ISSUE TITLE
"cannot open device with path \\?\hid#vid_045e&pid..."

### ISSUE THREAD

**Issue by lucasfcosta** [andrew/node-xbox-controller#28] opened 2015-01-28 22:29 UTC
I've just tried yo run your sample script (described on your README file) and I can't get it to run.

Everytime I try to do so, this appears: 
![error](http://s9.postimg.org/q7mpv7kwf/error.png)

I've installed everything and the path displayed on the image above is the same as I get for the xbox controller when I run:

```
var HID = require('node-hid');
var devices = HID.devices();
console.log(devices);
```

I've tried running my command prompt as admin and the same thing occurs. Is there any solution for this?

**Comment by Jabbath** [comment] 2015-01-29 15:19
First thing, do you have the xbox driver running in the background? If you do, kill the process. I've also seen this problem before when node-hid didn't compile correctly. Make sure you have Visual Studio 2012 Express (works well for me, no clue if you'll fare as well with other VS versions) and python 2.7.3 properly installed and in the path. Then try re installing node-hid.

**Comment by lucasfcosta** [comment] 2015-01-30 10:54
I do have Visual Studio Express 2012 and Python 2.7.3 properly installed and in the path. I didn't try to kill the driver process, I will try it as soon as I get home.

Thanks @Jabbath !

**Comment by lucasfcosta** [comment] 2015-01-31 23:38
@Jabbath , it isn't working yet.
I've done everything you said, installed Visual Studio 2012 express, Python 2.7.3 (It's also on the PATH) and I've closed the xbox driver too and ran the command prompt as admin.
The same error occurs.

Any ideas on how to fix this?

**Comment by Jabbath** [comment] 2015-01-31 23:47
I've no other troubleshooting tips unfortunately. This is probably an upstream bug with node-hid so you may want to ask there. You could also try another version of node-hid. This bug happened with me before but I was never able to properly pin the cause down.

**Comment by mapaiva** [comment] 2015-02-01 16:50
Hi Lucas,

Can be a permission problem. Try to run the prompt as administrator and execute your test script.

In node-hid already exists this issue:

https://github.com/node-hid/node-hid/issues/79

**Comment by lucasfcosta** [comment] 2015-02-01 21:27
@mapaiva I've already seen this issue and I couldn't get it to work in any way.
I did try to run the prompt as admin and the same error occurs.

**Comment by andrew** [comment] 2016-12-14 16:47
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.

**Closed by andrew** 2016-12-14 16:47 UTC
